// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idxivgubupjtdeptkyrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkeGl2Z3VidXBqdGRlcHRreXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODUzMDYsImV4cCI6MjA2NzA2MTMwNn0.TeXOJOK3s5pO2-5aw_7s5ueg3jKh4WoCT3pAgoXAvPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});